language: ruby

rvm:
- 2.1

install: gem install html-proofer

script:
- htmlproof ./ --only-4xx --check-favicon --check-html --file-ignore ["/.+\/d.+/", "./google67a5cd761da5a742.html", "./rollin/index.html", "./shikib/index.html"] --verbose

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true