language: ruby

rvm:
- 2.1

install: gem install html-proofer

script:
- htmlproof ./ --check-favicon --check-html --file-ignore "/.+\/d\/dx.+/" --verbose

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true