language: ruby

rvm:
- 2.1

install: gem install html-proofer

script:
- htmlproof ./ --only-4xx --check-favicon --check-html --file-ignore "/.*\/d.*/" --verbose

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true