# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: James Liu
email: james@jamesliu.ca
description: > # this means to ignore newlines until "baseurl:"
  Vancouver based developer and thing maker.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jamesliu.ca" # the base hostname & protocol for your site

timezone: America/Vancouver

permalink: /things/:title

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "post"

# Build settings
# markdown: kramdown

sass:
  style: compressed